[project]
name = "draw-this"
version = "0.1.0"
description = "Compact and self-contained image slideshow app meant for art/gesture practice sessions."
authors = [
    {name = "Meidarow",email = "60526952+Meidarow@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]
packages = []


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
